apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseService.name }}
  labels:
    {{- include "petclinic-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.databaseService.type }}
  ports:
    - port: {{ .Values.databaseService.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "petclinic-chart.selectorLabels" . | nindent 4 }}
