apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-auth
data:
  rootpassword: {{ .Values.databaseimage.credentials.root.password | b64enc }}
  rootusername: {{ .Values.databaseimage.credentials.root.username | b64enc }}