apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-petclinic-auth
data:
  petclinicpassword: {{ .Values.databaseimage.credentials.petclinic.password | b64enc }}
  petclinicusername: {{ .Values.databaseimage.credentials.petclinic.username | b64enc }}