apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic-chart.fullname" . }}
  labels:
    {{- include "petclinic-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webService.type }}
  ports:
    - port: {{ .Values.webService.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "petclinic-chart.selectorLabels" . | nindent 4 }}
